 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: backend
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /
 spec:
   rules:
   - host: backend.multicloud12-8a2d3071712c7c965e5501bbbe7f8585-0001.eu-de.containers.appdomain.cloud
     http:
       paths:
       - path: /
         backend:
           serviceName: backend
           servicePort: 8080
